title: "CCI and Key Economic Indicators"
description: "Modeling and forecasting the Consumer Confidence Index using macroeconomic data."
theme: jekyll-theme-cayman  # or minimal, slate, etc.
show_downloads: false
